version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped
